# Introducción:


Las nuevas dinámicas de migración, conflicto interétnico, diferencias de clase socioeconómica y segregación social son de manera creciente puestas en confrontación en el debate público y cada vez más estudiadas por las Ciencias Sociales. Aceptar la creciente diversidad social que se origina a partir de los procesos de modernización y globalización implica promover una sociedad más inclusiva, respetuosa y equitativa, donde se acepte a las personas por quienes son, independientemente de sus diferencias culturales, étnicas, religiosas o de clase. Aprender a aceptar y valorar la diversidad puede ayudar a las personas a desarrollar habilidades para la vida, como la empatía y la tolerancia. Hasta ahora, las investigaciones en Sociología se han centrado frecuentemente en el análisis de la posición que ocupan distintos grupos sociales dentro de la estructura social y de los desafíos que enfrentan para lograr integrarse en la sociedad [@young_justicia_2000; @wade_raza_2000; @viverosvigoya_interseccionalidad_2016]. Al profundizar en esta línea de investigación se han dejado de lado dos elementos fundamentales. Por un lado, se ha estudiado en menor medida el proceso de inclusión social en las escuelas [@blanco_equidad_2006] y la percepción que tienen los estudiantes sobre los demás grupos al relacionarse con ellos en su vida cotidiana, en el sentido de si aceptan o rechazan a determinados grupos sociales que son distintos al grupo de pertenencia en un espacio externo a la escuela, esto es, en sus vecindarios. Por otro lado, ha ido cobrando reciente relevancia el proceso mediante el cual se aprenden o reproducen las actitudes de las personas en relación con la aceptación o rechazo de determinados grupos sociales y la importancia de la escuela [@sandoval-hernandez_teaching_2018; @malak-minkiewicz_influences_2021] y la familia [@santanderramirez_preferencias_2020; @bandura_sociallearning_1969] en este proceso. Los procesos de socialización refieren a las formas en que los jóvenes aprenden y se adaptan a las normas, valores y comportamientos que se esperan de ellos en la sociedad. En la escuela, los estudiantes pueden estar expuestos a una amplia gama de culturas, creencias y experiencias, que resultan fundamentales para brindar oportunidades para que los estudiantes aprendan y aprecien la diversidad dentro de su escuela y comunidad. De esta forma, esta investigación pretende abordar los distintos procesos de socialización que están implicados en el aprendizaje de actitudes de aceptación o rechazo hacia diferentes grupos sociales en los vecindarios que habitan los estudiantes.

Siguiendo el panorama mundial, con el aumento sostenido del desarrollo económico de los últimos años, se ha pasado de demandas sociales que apuntan a valores de supervivencia (demandas socioeconómicas, derechos sociales, acceso a servicios básicos, etc.) hacia demandas de auto expresión, creatividad y democratización que ayudan a reorganizar las normas sexuales, los roles de género, los valores familiares, la religiosidad, la relación de las personas con la naturaleza y sus actividades comunitarias [@inglehart_Modernization_2001], como tal, se han planteado importantes desafíos en términos de Democracia, Ciudadanía y Cohesión Social. En una investigación internacional de 21 países con datos de la Encuesta Mundial de Valores, @vala_youth_2010 demuestra que los jóvenes son más tolerantes que las personas mayores hacia grupos estigmatizados y grupos percibidos como racial o étnicamente diferentes. En Chile, diversas investigaciones han dado cuenta de la relevancia de estudiar la diversidad social en el contexto escolar, ya sea por el aumento de la matrícula de estudiantes migrantes a nivel nacional [@caqueo-urizar_discriminacion_2019; @bustosgonzalez_gestion_2018; @alarcon-leiva_migracion_2021; @gelber_mitos_2021; @jimenezvargas_modelos_2014; @mera-lemp_school_2020], por el aumento de los conflictos interétnicos [@figueiredo_impact_2020; @webb_indigenous_2015] o por los conflictos de clase y segregación social [@gonzalez_acceso_2016; @rodrigo_social_2021; @hernandez_eleccion_2015].

Abordar el aprendizaje de actitudes hacia la aceptación social de jóvenes en edad escolar implica posicionar esta investigación bajo un incremento de la diversidad social que plantea importantes desafíos para los Estados-nación a nivel global en términos de políticas públicas, ya sea por sus implicancias gubernamentales, territoriales y socioeconómicas o por los nuevos requisitos que se originan en los distintos sistemas educativos a partir de demandas por inclusión y tolerancia de una población estudiantil diversa. En Chile se han suscrito distintos tratados internacionales que pretenden resguardar la diversidad (convenciones de DDHH, convenciones de Derechos del niño y el convenio 169 de la Organización Internacional del Trabajo) y que se han traducido en distintas políticas educativas que tienen por objetivo apoyar la inclusión de distintos sectores de la sociedad en el sistema educativo. 

Dentro de este ámbito destacan la ley de inclusión escolar que regula, entre otras cosas, la admisión equitativa de los y las estudiantes -sin distinción de clase ni selección- en los establecimientos educativos [@bibliotecadelcongresonacional_ley_2015] y el Programa de Educación Intercultural Bilingüe (PEIB) que tiene sus orígenes en la década de 1990 y una consolidación entre 2010 y 2016 y que pretende generar las condiciones para que las comunidades educativas, que atienden a estudiantes indígenas y no indígenas, sean partícipes de procesos sociales inclusivos, que desarrollen nuevas competencias al considerar en sus procesos formativos otras formas de ver y entender el mundo y que reconozcan, valoren y se ajusten a estos orígenes culturales diversos [@ministeriodeeducacion_Programa_2017]. Por otra parte, dentro del sistema escolar chileno la matrícula migrante ha aumentado en un 616% entre 2014 y 2016, y se ha triplicado desde 2016 [@roessler_acceso_2020], pero no se han generado políticas o programas específicos de esta materia.

Los aprendizajes que se le adjudican a la educación ciudadana en las escuelas pretenden dar respuesta a la necesidad de preparar a las nuevas generaciones para la vida en democracia y sus requerimientos morales y cognitivos [@cox_objetivos_2015]. La nueva ley de Formación Ciudadana (ley n° 20.911) dispone que todos los establecimientos educacionales deben diseñar un Plan de Formación Ciudadana que brinde a los estudiantes la preparación necesaria para asumir una vida responsable en una sociedad libre y de orientación hacia el mejoramiento integral de la persona humana, como fundamento del sistema democrático, la justicia social y el progreso [@bibliotecadelcongresonacional_plan_2016]. Entre sus principales objetivos, esta nueva ley busca promover la comprensión y análisis del concepto de ciudadanía y los derechos y deberes asociados a ella, además de fomentar en los estudiantes la valoración de la diversidad social y cultural del país y fomentar en los estudiantes la tolerancia y el pluralismo [@bibliotecadelcongresonacional_plan_2016].

Sin embargo, la tolerancia orientada hacia la existencia de una diversidad social marca una diferencia entre la aceptación, respeto y apreciación de la diferencia y la inclusión homogeneizante de los distintos grupos sociales dentro de las escuelas, ya que la definición de interculturalidad que se ha incluido en el sistema educativo es funcional al estatus quo al absorber a la diferencia y homogenizarlos [@riedemann_Desde_2020]. De esta forma, se invisibiliza y reproduce una discriminación basada en procesos de racialización, generización y diferenciación en términos de clase, acercándose más a la idea de multiculturalismo que a la de interculturalidad [@stefoni_Educacion_2016a]. Esta confusión en el horizonte de la educación intercultural produce una ineficacia de las políticas emprendidas y repercute en una incapacidad de generar una sociedad que acepte la diversidad y que establezca relaciones de cooperación entre sus diversidades [@donosoromo_INTERCULTURALIDAD_2006]. Lo anterior provoca que, en la práctica, antes que buscar una coexistencia de las diversidades, en el sistema educativo chileno se busca que los diferentes grupos sociales se integren a la sociedad nacional para que así obtengan los beneficios que ella reporta a todos sus ciudadanos [@donosoromo_INTERCULTURALIDAD_2006]. Esto provoca una contradicción en los establecimientos educacionales ya que se les pide valorar la diversidad social y cultural en las aulas mientras que, al mismo tiempo, se les exige responder a mecanismos de rendición de cuentas estandarizados que no dan cuenta de la diversidad [@riedemann_Desde_2020].

De esta forma, si bien los procesos de socialización se han amplificado y complejizado junto con los procesos de modernización y globalización, el rol de la escuela y la familia siguen siendo los principales agentes de socialización. Para la sociología la comprensión de la educación como un agente de socialización de las generaciones más jóvenes resulta fundamental, mientras que el rol de la familia ha sido estudiado en menor medida dentro de esta disciplina, sino más bien desde la psicología social. Así, las investigaciones sobre tolerancia e inclusión en población juvenil frecuentemente se han enfocado en problemáticas relacionadas con los flujos migratorios y su inserción en el sistema educativo de cada país, centrándose en cómo las escuelas permiten el ingreso e inclusión de distintos estudiantes en el sistema educativo [@bellei_estudio_2013; @ortiz_Actitudes_2016; @stefoni_Educacion_2016a] o en cómo las escuelas son capaces de influir en la (in)tolerancia y prejuicio hacia inmigrantes, minorías étnicas o disidencias sexuales [@lee_Tolerated_2014; @maurissen_Classroom_2020; @trevino_Influence_2018]. En cuanto al rol de la familia, algunas investigaciones han dado cuenta del efecto de las actitudes de los padres en el conflicto interétnico de su descendencia [@medjedovic_intergroup_2021], sobre las actitudes de los estudiantes hacia uno o más grupos subalternos según el grado de tolerancia [@farkac_Tolerance_2020] y de la participación política parental en el compromiso político de las nuevas generaciones [@bacovsky_raising_2021]. 

Además, en sociedades desiguales como la chilena, los recursos socioeconómicos funcionan como un mecanismo de diferenciación a nivel general donde se ha dado cuenta del rol predominante de los recursos socioeconómicos de las familias como un agente diferenciador del logro académico [@bellei_estudio_2013] y de la importancia de la elección de escuela en la construcción y reproducción de la segregación y estratificación del sistema escolar [@hernandez_eleccion_2015]. Más aún, @easterbrook_tackling_2021 señala que algunos grupos de estudiantes, generalmente aquellos que han sufrido debido a la desigualdad histórica en la sociedad, experimentan sentimientos de amenaza a su identidad social y la sensación de que su identidad es incompatible con el éxito educativo, contribuyendo sustancialmente a las desigualdades en los resultados educativos entre grupos, incluso más allá de las desigualdades económicas, históricas y estructurales.

Esta investigación pretende comprender cómo los procesos de socialización política de actitudes en la familia y la escuela se articulan entre sí y producen las disposiciones para excluir o aceptar a determinados grupos sociales. Así, la pregunta de investigación que guía este estudio es ¿en qué medida los distintos procesos de socialización son capaces de influir en las actitudes de las y los jóvenes estudiantes chilenos hacia la diversidad en sus vecindarios?


## Objetivo general

Analizar el rol que poseen la familia y la escuela como agentes de socialización política de actitudes en jóvenes estudiantes chilenos.

## Objetivos específicos

1.	Determinar en qué medida los/as estudiantes chilenos de ciclo básico aceptan o rechazan que diferentes grupos sociales vivan en sus vecindarios.

2.	Analizar el rol de la familia en la socialización política de actitudes hacia la diversidad social.

3.	Analizar el rol de la escuela en la socialización política de actitudes hacia la diversidad social.
