
```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

# Aceptar la diversidad en el vecindario

En Chile, las desigualdades interaccionales se han convertido en las desigualdades más percibidas y rechazadas por la población [@araujo_igualdad_2013]. Este tipo de desigualdades refieren a la manera en que las personas son tratadas por otros individuos o instituciones en las interacciones sociales ordinarias y concretas [@araujo_percepcion_2019]. Para @araujo_percepcion_2019 se ha instalado una *malignización de la otredad*, en que se constituye al otro como una amenaza y adversario, quebrando la noción de un espacio común y dando un marco de confrontación y disputa a las relaciones ordinarias entre los habitantes de la ciudad. De esta forma, @castells_globalizacion_2005 indica que el principio identitario dominante en América Latina es la identidad nacional, construida en torno a un Estado-nación que impulsaba un proyecto de desarrollo y una especificidad frente al resto de los países. Así, en la medida en que el Estado-nación se inserta en la globalización y se despega de sus bases tradicionales, “la separación entre Estado y nación lleva a una crisis de la identidad nacional como principio de cohesión social” [@castells_globalizacion_2005, p. 40].

Como resultado, @castells_globalizacion_2005 plantea que la identidad se convierte en un principio débil que no basta para construir el sentido de la vida colectiva y son suplantadas por el individualismo legitimado por el mercado, que se convierte en fuente de racionalidad y de proyecto, a la vez que se crean identidades comunitarias más fuertes, lo que conlleva el resurgimiento de la religión o identidades étnicas. Ante esta problemática, la Teoría de la Identidad Social ofrece un marco conceptual que permite explicar los procesos grupales y las relaciones intergrupales en términos de la interacción de los procesos sociales cognitivos, interactivos y societarios, en el que se ubica la autoconcepción identitaria en el centro de esta dinámica [@hogg_social_2016]. Esta interacción intergrupal se concibe como un recurso funcional que emerge en el seno de condicionantes contextuales e individuales concretos con el objeto de proporcionar a cada individuo las estrategias necesarias para afirmar su identidad [@scandroglio_teoria_2008]. Así, esta construcción de una identidad social define y evalúa el autoconcepto de uno mismo y cómo será tratado y pensado por los demás y, por lo tanto, cuando las personas hacen comparaciones entre su propio grupo y un grupo externo, se preocupan por asegurarse de que su propio grupo sea positivamente distintivo, claramente diferenciado y evaluado más favorablemente que los grupos externos [@hogg_social_2016].

De esta forma, la exclusión o rechazo de diferentes grupos sociales de un vecindario se comprende como una forma de cierre social en que se establecen barreras entre sectores o clases a partir de la construcción de identidades, comunidades y la monopolización de oportunidades con el fin de excluir a otras personas de ese círculo o clase [@parkin_Marxismo_1984]. En esta misma línea, @tilly_desigualdad_2000 plantea que en cada sociedad existen desigualdades persistentes, ya que las desigualdades por “raza, género, etnia, clase, edad, ciudadanía, nivel educacional y otros principios de diferenciación aparentemente contradictorios, se forman mediante procesos sociales similares y son, en una medida importante, organizacionalmente intercambiables" [@tilly_desigualdad_2000, p. 23]. Por un lado, estas desigualdades, más allá de las frecuentes formas de violencia explícitamente racista, tienden a materializarse en no tener acceso o tener un acceso menor al país, ciudad, barrio, vivienda, bares, política y/o medios de comunicación [@vandijk_Racismo_2013]. @vandijk_Racismo_2013 señala que se trata de una práctica social diferenciada, generalmente denominada discriminación, que se basa en prejuicios e ideologías racistas sobre la superioridad de una mayoría y la inferioridad de una minoría. Por otro lado, @diez-nicolas_Exclusion_2019 plantean que se trata de formas de exclusión social que frecuentemente se relacionan con conceptos como estigma, discriminación y prejuicio. No obstante, reducir o intensificar ciertas actitudes tendrá poco efecto sobre estas desigualdades persistentes, por lo que el foco debe estar puesto en los mecanismos sociales que producen esta desigualdad [@tilly_desigualdad_2000].

Medir la (in)tolerancia es un debate sostenido dentro de distintas disciplinas, que generalmente confluyen en dos enfoques centrales. Por un lado, se ha propuesto medir la tolerancia hacia grupos subalternos tales como migrantes, minorías étnicas y mujeres a partir de un enfoque de derechos [@miranda_Political_2018; @trevino_Influence_2018], de prejuicios [@meeusen_ParentChild_2015; @weber_educational_2020] y como una amenaza material y/o simbólica [@raijman_Perceived_2004]. Por otro lado, @diez-nicolas_Exclusion_2019 plantean que se trata de formas de exclusión social que frecuentemente se relacionan con conceptos como estigma, discriminación y prejuicio. Asimismo, @tendam_Measuring_2011 proponen que, para jóvenes, las actitudes de ciudadanía se manifiestan en las tareas sociales cotidianas. En la presente investigación se propone medir la tolerancia a partir de la aceptación o rechazo de que distintos grupos sociales vivan en el mismo vecindario que los estudiantes encuestados. Aceptar la diversidad en el vecindario refiere, por lo tanto, a formas de no exclusión de distintos grupos subalternos tradicionalmente marginados de la esfera social. En concreto, esta perspectiva teórica permite abordar si los estudiantes aceptan o rechazan que vivan en su vecindario personas de origen indígena, de distinto país, distinta región, distinta orientación sexual, distinta clase social, distinto color de piel y distinta religión.


## Procesos de socialización política de actitudes

A través de procesos de socialización diferenciados y continuos en el tiempo se producen distintos condicionamientos asociados a una clase particular de condiciones de existencia [@bourdieu_sentido_2007]. A partir de esto, si bien los planteamientos de @bourdieu_sentido_2007 podrían explicar la disposición de los individuos a generar y reproducir prácticas de exclusión social hacia distintos grupos sociales, no permiten comprender el modo en que se generan estas disposiciones. Es así como @archer_teoria_2009 plantea la problemática que ha tenido la sociología de la educación al centrarse solo en las prácticas y procesos que ocurren dentro de la escuela y no reconocer que “tanto los profesores como los alumnos están inmersos en relaciones socioculturales más amplias que traen consigo a la sala de clase” [@archer_teoria_2009, p. 39]. Esto implica que existe una interacción entre el contexto y las actividades sociales, pero que estas no covarían en el tiempo, sino que están desfasadas la una de la otra. Para @lahire_teoria_2012 resulta relevante comprender el mundo social a escala del individuo al mismo tiempo que se comprenden las condiciones sociales (y discursivas) de producción del individuo moral e ideológico, porque son elementos socialmente producidos. En este caso, el objetivo de esta investigación es comprender cómo los diferentes modos de socialización se articulan entre sí y producen las disposiciones para excluir o aceptar a determinados grupos sociales, ya que “los individuos socializados pueden haber interiorizado de manera duradera un cierto número de hábitos y, sin embargo, no tener ningún deseo particular de aplicarlos” [@lahire_teoria_2012, p. 87]. 

Para la sociología en general y la sociología de la educación en particular, la articulación de los procesos de socialización se concebirían como una sociología de los modos de socialización (escolares y extraescolares), articulándose con una sociología del conocimiento, para así poder comprender a grandes rasgos una disposición a partir de la reconstrucción de su génesis [@lahire_teoria_2012]. Esto es, abordar de manera articulada el rol de la familia y la escuela en la socialización política de actitudes hacia la diversidad social y el contexto en que estas se producen.

Al articular los diferentes modos de socialización, @aedohenriquez_habitus_2015 señala que es relevante tener en consideración la idea de Estrategia de Bourdieu, ya que esta implica ponerse a sí mismo en relación con otros, en situaciones propias del campo, en que las expectativas socializadas sobre su posición con respecto a otros entran en interrogación. La idea de Estrategia de Bourdieu refiere a que "en el mundo social actuamos conforme a ciertas inclinaciones que hemos incorporado a lo largo de nuestra experiencia social, en el marco de los procesos de socialización, inclinaciones o disposiciones que actúan como facilitadores de nuestras prácticas o de nuestros actos" [@aguilar_habitus_2017, p. 280].

Así, los grupos familiares estratégicamente seleccionan escuelas y vecindarios en los que integrar a sus hijos de acuerdo con sus disposiciones, esto es, que son capaces de elegir el espacio social en que socializarán a sus hijos. De la misma forma, la disposición hacia la exclusión -y hacia el cierre social que conlleva- marcaría dos momentos temporales. Por un lado, refiere a una expresión de los procesos de socialización familiares previos y, por otro lado, expresan las condiciones familiares objetivas que condicionan el proceso de socialización actual.

### Socialización política familiar de actitudes hacia la diversidad social.

El proceso de socialización política familiar se concibe como prácticas de crianza o estrategias de socialización concretas que buscan modelar las conductas de sus hijos e hijas según las propias valoraciones y personalidades que se estimen como positivas para la integración y el desenvolvimiento social en el futuro [@ramirez_padres_2005]. De esta forma, las familias reproducen y socializan valores a través de un proceso de transmisión de actitudes que permite asegurar la perpetuación del grupo social y la conservación del estatus y el privilegio [@bourdieu_reproduccion_1998; @bernstein_theoretical_2005].

Dentro de las estrategias del proceso de socialización política familiar se han reconocido dos elementos. En primer lugar, @lipset_hombre_1997 plantea la importancia de las condiciones socioeconómicas objetivas de la familia en el proceso de adquisición de valores y prácticas democráticas. En segundo lugar, para @bandura_sociallearning_1969 la teoría del aprendizaje social implica que las actitudes y comportamientos de los padres inciden sobre los intereses y modos de comportamiento de sus hijos, planteando así la necesidad de estudiar la transmisión intergeneracional de actitudes como proceso de socialización.

En este sentido, diferentes investigaciones han dado cuenta del rol predominante que poseen los recursos socioeconómicos como condicionante de las expectativas de participación política de los estudiantes [@castillo_Social_2014] y, específicamente, sobre las actitudes de los estudiantes hacia uno o más grupos subalternos según el grado de tolerancia [@farkac_Tolerance_2020], de prejuicios [@weber_educational_2020] o hacia la igualdad de derechos [@isac_Native_2012; @miranda_Political_2018]. Por un lado, @miranda_Political_2018 demuestran la importancia que posee el nivel educativo de los padres, el estatus ocupacional y la cantidad de libros en el hogar en la generación de actitudes positivas de los estudiantes hacia la igualdad de género y el estatus ocupacional de los padres y la cantidad de libros en el hogar sobre las actitudes hacia la igualdad de derechos para inmigrantes y minorías étnicas. Asimismo, @ortiz_Actitudes_2016 demuestra la importancia que poseen estos tres indicadores sobre las actitudes hacia la tolerancia social en general, mientras que @castillo_Social_2014 demuestran que padres con educación universitaria y la cantidad de libros en el hogar juegan un rol preponderante en las expectativas de participación política de los estudiantes. Por otro lado, @sincer_relationship_2020 demuestran que una mayor proporción de estudiantes de bajo nivel socioeconómico en las escuelas influyen negativamente en las competencias para lidiar con las diferencias sociales[^1]. Por último, sobre la transmisión intergeneracional de actitudes, se ha dado cuenta de la preponderancia de las actitudes de los padres en la disposición hacia el conflicto interétnico de sus hijos [@medjedovic_intergroup_2021], de cómo el historial de participación política parental influye en el compromiso político de las nuevas generaciones [@bacovsky_raising_2021] y que las familias de clase alta tienden a privilegiar valores más simbólico-relacionales, como los buenos modales y el respeto por los demás, mientras que las clases bajas privilegiarían transmitir valores de ascenso social, como el trabajo duro y el ahorro [@santanderramirez_preferencias_2020]. De esta forma, el proceso de socialización política familiar se refleja en las siguientes hipótesis: 

[^1]: @sincer_relationship_2020 señalan que *dealing with differences* refiere al conocimiento, actitudes y habilidades para interactuar con las diferencias sociales.

* H1: Estudiantes que provienen de familias con mayores recursos socioeconómicos poseen un mayor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

* H2: Estudiantes que provengan de familias en que sus padres acepten en mayor medida que distintos grupos sociales vivan en sus vecindarios, poseerán un mayor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

### Socialización política de actitudes hacia la diversidad social en la escuela.

Dentro de la investigación sobre socialización política de actitudes en la escuela se tiende a adjudicar al sistema educacional el objetivo de “suscitar y desarrollar al niño cierto número de estados físicos, intelectuales y morales que requieren en él tanto la sociedad política en su conjunto como el medio ambiente específico al que está especialmente destinado” [@durkheim_educacion_1999, p. 60], y que la función socializadora de la escuela se resume en que “consiste en el desarrollo dentro de cada individuo de aquellas habilidades y actitudes que constituyen los requisitos esenciales para su futuro desenvolvimiento en la vida” [@parsons_clase_1976, p. 65]. En esta línea, investigaciones recientes continúan enmarcándose en este rol de la escuela como agente formador de ciudadanos [@cox_Aprendizaje_2015; @groof_Influence_2008; @trevino_Influence_2017], resaltando las capacidades que tienen las escuelas para contribuir en el desarrollo cívico y las actitudes democráticas de los jóvenes estudiantes. 

La escuela se comprende como el espacio primordial de socialización y de encuentro entre personas de distintas realidades, funcionando como una micro sociedad [@groof_Influence_2008]. Las características estructurales de las escuelas son una dimensión clave para explicar los diferentes resultados que poseen los estudiantes [@trevino_Influence_2018]. En cierta medida esto se explica por la forma en que los estudiantes de diferentes estratos socioeconómicos se distribuyen a través de las escuelas según su tipo de administración [@bellei_estudio_2013] y por los conocimientos, habilidades y valores sociales que estas instituciones le logran otorgar a sus estudiantes [@groof_Influence_2008]. Específicamente, tanto las escuelas como las salas de clases pueden diferir entre sí en cuanto a sus valores y normas comunes, en cómo los estudiantes interactúan entre sí y cómo los profesores se acercan y tratan a los estudiantes [@bayramozdemir_How_2020].

En primer lugar, el conocimiento cívico y las oportunidades que brinden las escuelas para su aprendizaje es un elemento esencial para la socialización de valores y normas comunes. El conocimiento cívico refiere a la información cívica y ciudadana aprendida que los estudiantes utilizan cuando se involucran en tareas más complejas que les ayudan a entender de mejor forma el mundo político [@carstens_Overview_2018], mientras que @sampermans_Back_2020 señalan que el conocimiento cívico depende directamente de las oportunidades de aprendizaje cívico que logren promover las escuelas. Diversos autores han demostrado que el conocimiento cívico influye de manera positiva sobre las actitudes de estudiantes hacia la tolerancia de personas inmigrantes [@isac_Native_2012; @groof_Influence_2008; @torney-purta_How_2008].

En segundo lugar, una de las características estructurales fundamentales de las escuelas es la disposición de espacios de discusión. En las aulas donde los estudiantes están expuestos al mundo real de los problemas políticos, por medio del discurso y el debate tienen la oportunidad de luchar por cuestiones políticas y sociales, aprendiendo el elemento vital de la democracia participativa [@campbell_Voice_2008]. Por lo tanto, es evidente que esto solo se puede lograr cuando se promueve y se resguarda que exista comunicación y diálogo entre los alumnos de diferentes nacionalidades, etnias, lenguas, colores de piel, estratos socioeconómicos e intereses [@riedemann_Desde_2020]. Se ha demostrado que este indicador influye sobre las actitudes de los estudiantes hacia la tolerancia de inmigrantes [@eckstein_school_2021; @maurissen_Classroom_2020; @groof_Influence_2008; @isac_Native_2012], sobre las actitudes de los estudiantes hacia la igualdad de derechos para inmigrantes, minorías étnicas y mujeres [@trevino_Influence_2018; @trevino_Influence_2017], sobre las actitudes cívicas de los estudiantes en general [@barber_Profiles_2020 @trolian_shaping_2022] y sobre la formación de conocimiento cívico en los estudiantes [@sampermans_Back_2020; @barber_Immigrant_2015]. De esta forma, el rol de la escuela en la socialización política de actitudes se resume en las siguientes hipótesis: 

* H3: Estudiantes que poseen un mayor conocimiento cívico presentan un mayor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

* H4: Estudiantes que perciben una mayor apertura a la discusión en sus aulas presentan un mayor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

Finalmente, debido al rol del sistema educacional al alero de las nuevas políticas públicas de inclusión y Educación ciudadana, de manera exploratoria se plantea que las escuelas son capaces de mitigar las desigualdades sociales de origen y/o potenciar las actitudes positivas en la formación de las actitudes de los estudiantes hacia la aceptación de la diversidad en sus vecindarios. Esto implica que las escuelas cumplen un rol moderador en la generación de las actitudes de los estudiantes y, por lo tanto, se plantea la siguiente hipótesis:

* H5: El proceso de socialización en las escuelas cumple un rol moderador sobre la influencia de la socialización de la familia en las actitudes de los estudiantes hacia la aceptación de la diversidad en sus vecindarios.

### Implicancias del vecindario en la socialización política de actitudes hacia la diversidad social.

El incremento de la diversidad social en los vecindarios tiene distintos efectos sobre la convivencia social y la tolerancia de lo que se percibe como diferente. Por un lado, en vecindarios heterogéneos, con una mayor diversidad de contactos sociales y una mayor interacción entre individuos de diversos orígenes, se deberían generar las condiciones para tener un mayor grado de prosocialidad [@diprete_segregation_2011], sin embargo, también se ha argumentado que una mayor interacción entre grupos distintos podría reforzar los prejuicios [@putnam_pluribus_2007]. Por otro lado, la marcada segregación urbana del contexto chileno que sienta las bases para la consolidación de vecindarios homogéneos es bastante desfavorable para el contacto intergrupal positivo y la reducción de prejuicios [@garreton_city_2017]. En esta misma línea, @garreton_social_2021 muestran que el capital social, es decir, una mayor cantidad de vínculos y contactos positivos, está negativamente correlacionado con la diversidad socioeconómica, pero positivamente correlacionado con una mayor diversidad de inmigrantes, lo que sugiere la importancia de diferenciar ambos contextos en el desarrollo del capital social.

En cada vecindario, los distintos patrones de segregación están asociados con grandes diferencias en el acceso al mercado laboral y a otros recursos culturales y sociales [@fernandez_breaking_2016]. Así, según @baldassarri_diversity_2020, la competencia entre *minorías* es mayor en los lugares donde estas son más numerosas. Esto se debe a que las minorías étnicas y raciales a menudo no pueden competir por trabajos de alta calidad, incluso estando calificadas para ellos, y en su lugar se ven obligadas a competir por trabajos de menor calidad o informales, lo que trae como consecuencia que las personas de clases sociales bajas puedan sentir a las minorías como amenazas con más frecuencia que la gente de clases sociales más altas [@baldassarri_diversity_2020]. Este sentimiento de amenaza producido por la competencia por recursos y trabajos tiende a disminuir la confianza entre grupos distintos, dificultando así el desarrollo de vínculos sociales [@cote_untangling_2009].

De esta forma, las características específicas de cada vecindario podrían afectar de diferentes maneras las actitudes de los y las estudiantes, dependiendo de sus condiciones materiales, de la disponibilidad de recursos y de la calidad y cantidad de los contactos e interacciones con personas de diferentes grupos. Por ejemplo, se ha estudiado que una mayor segregación residencial se asocia con actitudes negativas hacia inmigrantes y en personas nativas de territorios donde ha habido un gran cambio en la diversidad en los últimos años [@kawalerowicz_too_2021], el entorno físico del vecindario, como la accesibilidad a diferentes tipos de espacios públicos urbanos contribuye a una actitud más positiva hacia la inclusión de inmigrantes al fomentar una interacción vecinal más fuerte [@wang_neighborhood_2022] o que en territorios con alta confianza en extranjeros esta no se relaciona con la proporción de inmigrantes en la población del vecindario [@schonwalder_attitudes_2016]. Sin embargo, algunos de estos elementos escapan de los alcances de esta investigación y de la disponibilidad de datos, por lo que se plantean tres hipótesis sobre características de los vecindarios que podrían afectar si los y las estudiantes aceptan o rechazan que distintos grupos sociales vivan en sus vecindarios:

* H6: Estudiantes que viven en vecindarios con una mayor proporción de personas que se identifican con alguna etnia presentan un menor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

* H7: Estudiantes que viven en vecindarios con una mayor proporción de población inmigrante presentan un menor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.

* H8: Estudiantes que viven en vecindarios con un mayor promedio de escolaridad presentan un mayor grado de aceptación de la diversidad en sus vecindarios, manteniendo el resto de las variables constantes.
