# Discusión

Estos resultados son consistentes con algunas de las hipótesis planteadas. En primer lugar, en cuanto al proceso de socialización familiar, los resultados no permiten comprobar la hipótesis 1 sobre la relación entre los recursos socioeconómicos de la familia y un mayor grado de aceptación de la diversidad en su vecindario. Por el contrario, el único resultado que posee una asociación estadísticamente significativa indica que estudiantes que poseen apoderados con un nivel de educación media aceptarían menos la diversidad en su vecindario en comparación con aquellos estudiantes que poseen apoderados con educación básica. En relación con las actitudes de los apoderados los resultados permiten corroborar la hipótesis planteada (H2), es decir, aquellos estudiantes que provienen de familiar con padres que aceptan en mayor medida que distintos grupos sociales vivan en sus vecindarios, también poseen un mayor grado de aceptación de la diversidad en sus vecindarios.

En segundo lugar, los resultados permiten comprobar las hipótesis relacionadas con el proceso de socialización escolar. Estudiantes que poseen un nivel de conocimiento cívico medio y alto poseen un mayor grado de aceptación de la diversidad en sus vecindarios en comparación con estudiantes que poseen un nivel de conocimiento cívico bajo; esto es consistente con la hipótesis 3. En relación con el índice de apertura a la discusión en las salas de clases, los resultados indican que estudiantes que perciben en mayor medida un ambiente abierto a la discusión y al debate dentro del aula poseen un mayor grado de aceptación de la diversidad, lo que permite comprobar la hipótesis 4.

En tercer lugar, los resultados de las estimaciones de los modelos multinivel no permiten comprobar las hipótesis planteadas. Las características de las comunas en que residen los estudiantes, como la proporción de personas que se identifican con alguna etnia, la proporción de inmigrantes y el promedio de escolaridad de la comuna no afectan en el proceso de socialización de actitudes de los y las estudiantes.

Para evaluar la hipótesis 5 (si la escuela puede mitigar o potenciar la relación de las actitudes de los apoderados y las actitudes de los estudiantes), 

