# Conclusiones

Esta investigación tenía por objetivo evaluar en qué medida los procesos de socialización influyen en las actitudes hacia la diversidad social de estudiantes chilenos. En concreto, se evaluó si los procesos de socialización familiar y escolar, además de algunas características territoriales, podían influir en las actitudes de los estudiantes. En términos generales los resultados permiten identificar el rol de la transmisión intergeneracional de actitudes dentro del proceso de socialización familiar y el rol del conocimiento cívico y la percepción de apertura a la discusión en el aula dentro del proceso de socialización escolar.

De acuerdo con la literatura las características socioeconómicas de las familias poseen un rol preponderante en el proceso de formación de los estudiantes, sin embargo, los resultados de esta investigación no van en línea con este supuesto, sino que son las actitudes de los apoderados las que influyen en las actitudes de los estudiantes. Esto permite sustentar la hipótesis de la transmisión intergeneracional de la desigualdad política, donde solo aquellos estudiantes con padres más tolerantes generarán actitudes tolerantes dentro del proceso de socialización familiar. De esta forma se generan importantes desafíos para el proceso posterior de socialización escolar, ya que será tarea de las escuelas producir equitativamente estudiantes más tolerantes. 

En cuanto al proceso de socialización escolar, el nivel de conocimiento cívico es un factor clave en la generación de actitudes favorables hacia la diversidad social en los estudiantes. Esto da cuenta de la importancia que debe jugar el pluralismo de ideas y la tolerancia en el currículum escolar como valores que se comparten y promueven en la sociedad. La transmisión de actitudes tolerantes a partir del currículum indica que la Ley de Formación Ciudadana N°20.911, que tiene entre sus objetivos fomentar en los estudiantes la valoración de la diversidad social y cultural del país y la tolerancia y el pluralismo, posee un rol clave en asegurar que todos los estudiantes adquieran estas actitudes. De todas maneras, los análisis realizados dan cuenta de que la mayor cantidad de estudiantes con un Conocimiento cívico alto provienen de familias con apoderados que poseen educación superior, lo que problematiza aún más la desigualdad del sistema educacional chileno.

Asimismo, la percepción de apertura a la discusión en el aula también influye en las actitudes de los estudiantes, dando cuenta de la relevancia que poseen los espacios cotidianos de convivencia, discusión y debate dentro de las escuelas. Sin embargo, solo en las escuelas con una mayor percepción de apertura a la discusión se logra potenciar la relación entre las actitudes de los apoderados y los estudiantes. Esto indica a grandes rasgos que si las actitudes cívicas no se practican todos los días, insistiendo solo en el currículum escolar y dejando fuera los espacios cotidianos de convivencia de los y las estudiantes, se corre el riesgo de generar conocimientos lejanos a la experiencia real de los estudiantes y no subsanar las desigualdades de la transmisión intergeneracional de actitudes, ya que los resultados señalan que en aquellas escuelas donde no existe un ambiente favorable a la discusión y el debate es más difícil mejorar las actitudes de los estudiantes cuyos apoderados poseen una baja aceptación de la diversidad.

Una de las principales limitaciones de este estudio es la poca varianza que tienen las variables de tolerancia a cada uno de los grupos estudiados (antes de la construcción del índice) y que imposibilitan realizar un análisis más preciso de la dimensionalidad de la variable dependiente. Asimismo, no poseer datos de identificación de los vecindarios o unidades censales en que viven los estudiantes limita los resultados, ya que es posible que el nulo efecto de las variables territoriales se deba a que corresponden a agrupaciones comunales que no permiten medir el efecto real del contexto en que viven los estudiantes.

Finalmente, así como la discusión y el debate escolar influyen en las actitudes de los estudiantes, sería interesante problematizar e investigar si la participación en espacios extra-escolares, de los vecindarios y territorios, puede influir en la tolerancia y aceptación de la diversidad. Traspasar la Escuela como único formador de ciudadanos y conocer qué otros factores puedan influir en la socialización de actitudes es una agenda de investigación futura. 

En resumen, los resultados proveen evidencia adicional de acuerdo con factores y condiciones que tienen el potencial de ayudar a las escuelas y profesores a promover la tolerancia. Por lo tanto, las escuelas continúan teniendo un rol fundamental en el proceso de socialización de las nuevas generaciones y, en definitiva, el foco debe estar en que estos mecanismos sean transversales a todo el sistema educacional. De esta forma, será posible construir una sociedad más inclusiva, respetuosa y equitativa, donde se acepte y valore a las personas por quienes son, dentro y fuera de la escuela, e independiente de sus diferencias nacionales, culturales, étnicas, religiosas o de clase.