---
title: 'Aceptar la diversidad en el vecindario'
subtitle: "Procesos de socialización política de actitudes hacia la diversidad social en jóvenes estudiantes chilenos"
author: "Kevin Carrasco Quintanilla"
date: "`r Sys.Date()`"
institution: "Universidad de Chile"
degree: "Magister en ciencias sociales mención en sociología de la modernización"
advisor: "Profesor guía: Juan Carlos Castillo"
bibliography: aceptacion-diferencia.bib
biblio-style: apalike
link-citations: yes
linkcolor: blue
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 14pt
lof: True
lot: True
github-repo: "kevin-carrasco/aceptar-diferencia"
url: ""
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = FALSE,out.width = '75%',fig.pos= "H",fig.align = 'center')
# knitr::opts_knit$set(base.url = "../") #relative path for .html output file
# knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '',linesep = "")
options(knitr.graphics.error = FALSE)
# Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}
pacman::p_load(knitr, kableExtra, dplyr,flextable,pander)
```

```{r echo=FALSE }
is_word_output <- function(fmt = knitr:::pandoc_to()) {
  length(fmt) == 1 && fmt == "docx"
}

table_format = if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}

eval01 = if(is_html_output() | is_latex_output()) {T} else {F}


fullw = if(is_html_output()) {T} else if(is_latex_output()) {F}
fsize = if(is_html_output()) {14} else if(is_latex_output()) {8}
```

# Resumen