---
title: "Analisis descriptivo"
author: "Kevin Carrasco"
date: '2022-06-08'
output: html_document
---

```{r}
pacman::p_load(dplyr, ggplot2, sjPlot, summarytools, corrplot, ltm, ggpubr, ggmosaic, scales)
load("IPO/input/data/proc/data.RData")
load("IPO/input/data/proc/data_comuna.RData")
```


# Dependiente
```{r}
data_est <- dplyr::select(data, est_piel,
                                 est_clase,
                                 est_religion,
                                 est_orien_sexual,
                                 est_region,
                                 est_pais,
                                 est_indigena)

df <- dfSummary(data_est,
                plain.ascii = F,
                varnumbers = F, 
                graph.col = T, 
                style = "grid",
                headings = F)
df$Variable <- NULL # delete variable column
view(df,file = "desc01.html")
webshot(url ="desc01.html" ,file ="IPO/output/tables/desc01.png")
```

# Independiente
```{r}
data_comuna <- rename(data_comuna, cod_com_alu=p10comuna)

data <- left_join(data, data_comuna, by="cod_com_alu")

data$etnia2 <- round(data$prop_etnia*1000, 3)
data$inmigrante2 <- round(data$prop_inm*1000, 3)

data$civic <- sjlabelled::set_label(data$civic, 'Conocimiento cívico (clasificación ICCS)')
data$apdis_fa <- sjlabelled::set_label(data$apdis_fa, 'Índice apertura a la discusión en el aula')
data$apod_acc_div <- sjlabelled::set_label(data$apod_acc_div, 'Índice aceptación de la diversidad (apoderados)')
data$mean_apdis_fa <- sjlabelled::set_label(data$mean_apdis_fa, 'Promedio apertura a la discusión en el aula')
data$educacion_rec <- sjlabelled::set_label(data$educacion_rec, 'Nivel educacional apoderados')
data$libros_rec <- sjlabelled::set_label(data$libros_rec, 'Cantidad de libros en el hogar')
data$etnia2 <- sjlabelled::set_label(data$etnia2, 'Proporción de personas que se identifica con alguna etnia')
data$inmigrante2 <- sjlabelled::set_label(data$inmigrante2, 'Proporción de inmigrantes')
data$escolaridad <- sjlabelled::set_label(data$escolaridad, 'Promedio de escolaridad')


data_indep <- dplyr::select(data,
                            educacion_rec,
                              libros_rec,
                              apod_acc_div,
                              civic,
                              apdis_fa,
                            mean_apdis_fa,
                            etnia2,
                           inmigrante2,
                           escolaridad)


df2 <- dfSummary(data_indep,
                varnumbers = F, 
                graph.col = T, 
                style = "grid",
                headings = F)

df2$Variable <- NULL # delete variable column
view(df2,file = "desc02.html")
webshot(url ="desc02.html" ,file ="IPO/output/tables/desc02.png")
file.remove(c("desc01.html","desc02.html"))
```

# Visualización descriptivos

```{r}
div_est <- sjPlot::plot_stackfrq(dplyr::select(data, est_piel,
                                 est_clase,
                                 est_religion,
                                 est_orien_sexual,
                                 est_region,
                                 est_pais,
                                 est_indigena),
                                 geom.colors = c("coral", "cadetblue"),
                                 title = "¿Te molestaría tener vecinos que pertenecieran a los siguientes grupos?") +
  theme(legend.position="bottom")

ggsave(div_est, file = "IPO/output/graphs/div_est.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```

```{r}
div_apod <- sjPlot::plot_stackfrq(dplyr::select(data, apod_piel,
                                 apod_clase,
                                 apod_religion,
                                 apod_orien_sexual,
                                 apod_region,
                                 apod_pais,
                                 apod_indigena),
                                 geom.colors = c("coral", "cadetblue"),
                                 title = "¿Te molestaría tener vecinos que pertenecieran a los siguientes grupos?") +
  theme(legend.position="bottom")

ggsave(div_apod, file = "IPO/output/graphs/div_apod.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```
## estudiantes
```{r}
data$est_piel_rec <- as.numeric(data$est_piel)
data$est_clase_rec <- as.numeric(data$est_clase)
data$est_religion_rec <- as.numeric(data$est_religion)
data$est_orien_sexual_rec <- as.numeric(data$est_orien_sexual)
data$est_region_rec <- as.numeric(data$est_region)
data$est_pais_rec <- as.numeric(data$est_pais)
data$est_indigena_rec <- as.numeric(data$est_indigena)

corrplot.mixed(cor(dplyr::select(data, est_piel_rec,
                                 est_clase_rec,
                                 est_religion_rec,
                                 est_orien_sexual_rec,
                                 est_region_rec,
                                 est_pais_rec,
                                 est_indigena_rec),
                   method = "spearman",
                   use = "complete.obs"))
```

```{r}
ltm::cronbach.alpha(data %>%
  dplyr::select(est_piel_rec, est_clase_rec, est_religion_rec, est_orien_sexual_rec, est_region_rec, est_pais_rec, est_indigena_rec), na.rm=TRUE)
```

```{r}
data$est_piel_rec <- car::recode(data$est_piel_rec, "1=0; 2=1")
data$est_clase_rec <- car::recode(data$est_clase_rec, "1=0; 2=1")
data$est_religion_rec <- car::recode(data$est_religion_rec, "1=0; 2=1")
data$est_orien_sexual_rec <- car::recode(data$est_orien_sexual_rec, "1=0; 2=1")
data$est_region_rec <- car::recode(data$est_region_rec, "1=0; 2=1")
data$est_pais_rec <- car::recode(data$est_pais_rec, "1=0; 2=1")
data$est_indigena_rec <- car::recode(data$est_indigena_rec, "1=0; 2=1")

data <- data %>% rowwise() %>% mutate(est_acc_div = sum(est_piel_rec, est_clase_rec, est_religion_rec, est_orien_sexual_rec, est_region_rec, est_pais_rec, est_indigena_rec, na.rm = T))

summary(data$est_acc_div)
```

```{r}
ind_est <- sjPlot::plot_frq(data$est_acc_div,
                 type = "bar",
                 axis.title = "Aceptación de la diversidad en el vecindario
                 Fuente: Elaboración propia",
                 geom.colors = "coral")

ggsave(ind_est, file = "IPO/output/graphs/ind_est.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```



## apoderados

```{r}
data$apod_piel_rec <- as.numeric(data$apod_piel)
data$apod_clase_rec <- as.numeric(data$apod_clase)
data$apod_religion_rec <- as.numeric(data$apod_religion)
data$apod_orien_sexual_rec <- as.numeric(data$apod_orien_sexual)
data$apod_region_rec <- as.numeric(data$apod_region)
data$apod_pais_rec <- as.numeric(data$apod_pais)
data$apod_indigena_rec <- as.numeric(data$apod_indigena)

corrplot.mixed(cor(dplyr::select(data, apod_piel_rec,
                                 apod_clase_rec,
                                 apod_religion_rec,
                                 apod_orien_sexual_rec,
                                 apod_region_rec,
                                 apod_pais_rec,
                                 apod_indigena_rec),
                   method = "spearman",
                   use = "complete.obs"))
```

```{r}
ltm::cronbach.alpha(data %>%
  dplyr::select(apod_piel_rec, apod_clase_rec, apod_religion_rec, apod_orien_sexual_rec, apod_region_rec, apod_pais_rec, apod_indigena_rec), na.rm=TRUE)
```

```{r}
data$apod_piel_rec <- car::recode(data$apod_piel_rec, "1=0; 2=1")
data$apod_clase_rec <- car::recode(data$apod_clase_rec, "1=0; 2=1")
data$apod_religion_rec <- car::recode(data$apod_religion_rec, "1=0; 2=1")
data$apod_orien_sexual_rec <- car::recode(data$apod_orien_sexual_rec, "1=0; 2=1")
data$apod_region_rec <- car::recode(data$apod_region_rec, "1=0; 2=1")
data$apod_pais_rec <- car::recode(data$apod_pais_rec, "1=0; 2=1")
data$apod_indigena_rec <- car::recode(data$apod_indigena_rec, "1=0; 2=1")

data <- data %>% rowwise() %>% mutate(apod_acc_div = sum(apod_piel_rec, apod_clase_rec, apod_religion_rec, apod_orien_sexual_rec, apod_region_rec, apod_pais_rec, apod_indigena_rec, na.rm = T))

summary(data$apod_acc_div)
```

```{r}
ind_apod <- sjPlot::plot_frq(data$apod_acc_div,
                 title = "Índice aceptación de la diversidad (apoderados)",
                 type = "bar",
                 axis.title = "Cantidad de grupos que no le molestan",
                 geom.colors = "coral")
ggsave(ind_apod, file = "IPO/output/graphs/ind_apod.png",device = "png",width = 25,height = 13,dpi = "retina",units = "cm")
```

# Descriptivos bivariados

```{r}
# dicotomizar var dep
data = data %>% rowwise() %>%  
  mutate(est_act_dic = case_when(est_acc_div==7~"Acepta todos los grupos",
                                 est_acc_div<=6~"Rechaza uno o más grupos"
                                              ))
#dicotomizar educacion
data = data %>% rowwise() %>%  
  mutate(educacion_dic = case_when(educacion_rec=="Ed Basica"~"Menos que Educación superior",
                                                 educacion_rec=="Ed Media"~"Menos que Educación superior",
                                                 educacion_rec=="Ed Tecnica"~"Educación superior",
                                                 educacion_rec=="Universidad o posgrado"~"Educación superior",
                                                 educacion_rec=="Ns/Nr"~"Ns/Nr"))
table(data$educacion_dic)
data$educacion_dic <- factor(data$educacion_dic, levels = c("Menos que Educación superior", "Educación superior", "Ns/Nr"))

data = data %>% rowwise() %>%  
  mutate(civic_dic = case_when(civic=="Bajo nivel D"~"Nivel C y D",
                               civic=="Nivel D"~"Nivel C y D",
                               civic=="Nivel C"~"Nivel C y D",
                               civic=="Nivel B"~"Nivel A y B",
                               civic=="Nivel A"~"Nivel A y B"
                                              ))


plot_bivariado <- data %>% 
  filter(educacion_dic!="Ns/Nr") %>% 
  filter(!is.na(civic)) %>% 
  ggplot() +
  theme_bw() +
  geom_mosaic(aes(product(est_act_dic, civic_dic), 
                  fill= est_act_dic),
              show.legend = FALSE,
              na.rm = TRUE) +
  geom_mosaic_text(aes(x = product(est_act_dic, civic_dic), label = after_stat(.wt), as.label=TRUE)) +
  labs(y = "Actitudes estudiantes", x = "Conocimiento cívico") +
  facet_grid(educacion_dic~.)

plot_bivariado

ggsave(plot_bivariado, file="IPO/output/graphs/plot_bivariado.png")
```







```{r}
comuna = data %>% filter(!is.na(nom_com_alu)) %>% 
  group_by(nom_com_alu) %>%
  summarise(mean = mean(est_acc_div, na.rm = T))



comuna %>% filter(mean<=7) %>% 
  ggplot(aes(nom_com_alu, mean)) +
  theme_bw(base_size = 15) +
 # geom_point(size = 4) +
  geom_text(aes(label=nom_com_alu), check_overlap = TRUE) +
  xlab("comuna") +
  ylab("Actitudes de estudiantes") +
  scale_y_continuous(limits = c(0, 7))
```


```{r}
data %>% filter(nom_com_alu=="ï¿½IQUEN")

data %>% filter(nom_com_alu=="ï¿½Uï¿½OA")
```

