---
title: "03-analisis_multinivel"
author: "Kevin Carrasco"
date: "2022-08-11"
output: html_document
---

Este .rmd contiene el análisis multinivel realizado para evaluar las hipótesis establecidas en el proyecto de investigación.

* Cargar paquetes

```{r}
pacman::p_load(dplyr, ggplot2, sjPlot, summarytools, corrplot, ltm, lme4, stargazer, texreg, scales, webshot)
load("IPO/input/data/proc/data.RData")
load("IPO/input/data/proc/data_comuna.RData")
```

# Crear indices de aceptacion de la diversidad en estudiantes (dependiente) y apoderados (independiente)

## estudiantes
```{r}
data$est_piel_rec <- as.numeric(data$est_piel)
data$est_clase_rec <- as.numeric(data$est_clase)
data$est_religion_rec <- as.numeric(data$est_religion)
data$est_orien_sexual_rec <- as.numeric(data$est_orien_sexual)
data$est_region_rec <- as.numeric(data$est_region)
data$est_pais_rec <- as.numeric(data$est_pais)
data$est_indigena_rec <- as.numeric(data$est_indigena)

corrplot.mixed(cor(dplyr::select(data, est_piel_rec,
                                 est_clase_rec,
                                 est_religion_rec,
                                 est_orien_sexual_rec,
                                 est_region_rec,
                                 est_pais_rec,
                                 est_indigena_rec),
                   method = "spearman",
                   use = "complete.obs"))
```

```{r}
ltm::cronbach.alpha(data %>%
  dplyr::select(est_piel_rec, est_clase_rec, est_religion_rec, est_orien_sexual_rec, est_region_rec, est_pais_rec, est_indigena_rec), na.rm=TRUE)
```

```{r}
data$est_piel_rec <- car::recode(data$est_piel_rec, "1=0; 2=1")
data$est_clase_rec <- car::recode(data$est_clase_rec, "1=0; 2=1")
data$est_religion_rec <- car::recode(data$est_religion_rec, "1=0; 2=1")
data$est_orien_sexual_rec <- car::recode(data$est_orien_sexual_rec, "1=0; 2=1")
data$est_region_rec <- car::recode(data$est_region_rec, "1=0; 2=1")
data$est_pais_rec <- car::recode(data$est_pais_rec, "1=0; 2=1")
data$est_indigena_rec <- car::recode(data$est_indigena_rec, "1=0; 2=1")

data <- data %>% rowwise() %>% mutate(est_acc_div = sum(est_piel_rec, est_clase_rec, est_religion_rec, est_orien_sexual_rec, est_region_rec, est_pais_rec, est_indigena_rec))

data_comuna <- rename(data_comuna, cod_com_alu=p10comuna)

base <- merge(data, data_comuna, by="cod_com_alu")

base$etnia2 <- round(base$prop_etnia*10000, 3)
base$inmigrante2 <- round(base$prop_inm*10000, 3)

base$etnia2 <- sjlabelled::set_label(base$etnia2, 'Proporción de personas que se identifica con alguna etnia')
base$inmigrante2 <- sjlabelled::set_label(base$inmigrante2, 'Proporción de inmigrantes')
base$escolaridad <- sjlabelled::set_label(base$escolaridad, 'Promedio de escolaridad')

base <- base %>% dplyr::select(est_acc_div, educacion_rec, libros_rec, apod_acc_div, civic, apdis_fa, mean_apdis_fa, mrbd, escolaridad, etnia2, inmigrante2, cod_com_alu) %>% na.omit()
```

# primera estimacion (mrbd)

```{r}
reg0 <- lmer(est_acc_div ~ 1 + (1 | mrbd), data=base)
reg1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + (1 | mrbd), data=base)
reg2 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + (1 | mrbd), data=base)
reg3 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + (1 | mrbd), data=base)
reg4 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
```

```{r}
screenreg(list(reg0, reg1, reg2, reg3, reg4))
```

# Interacciones

```{r}
# actitudes apod x escuela
reg6 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*civic + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg7 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*mean_apdis_fa + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
# actitudes apod x territorio
reg8 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*inmigrante2 + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg9 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*etnia2 + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg10 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*escolaridad + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
# recursos x escuela
reg11 <- lmer(est_acc_div ~ educacion_rec*civic + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg12 <- lmer(est_acc_div ~ educacion_rec + libros_rec*civic + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg13 <- lmer(est_acc_div ~ educacion_rec*mean_apdis_fa + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
reg14 <- lmer(est_acc_div ~ educacion_rec + libros_rec*mean_apdis_fa + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd), data=base)
```

```{r}
screenreg(list(reg4, reg6, reg7, reg11, reg12, reg13, reg14))
```

```{r}
screenreg(list(reg11, reg12, reg13, reg14))
```

```{r results='asis', message=FALSE, echo=FALSE}  
htmlreg(list(reg1, reg2, reg3, reg4, reg7), 
         custom.model.names = c("Modelo 1",
                               "Modelo 2",
                               "Modelo 3",
                               "Modelo 4",
                               "Modelo 5"), 
        custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05",
        custom.coef.names = c("Intercepto", 
                              "Educación media <br> <i>(Ref. Básica)</i>",
                              "Educación técnica", 
                              "Universidad o posgrado",
                              "Educación Ns/Nr",
                              "Más de 25 libros <br> <i>(Ref. menos de 25)</i>", 
                              "Aceptación diversidad apoderados", 
                              "Conocimiento cívico D <br> <i>(Ref. Bajo nivel D)</i>", 
                              "Conocimiento cívico C",
                              "Conocimiento cívico B",
                              "Conocimiento cívico A",
                              "Discusión en sala de clases", 
                              "Promedio discusión en sala", 
                              "Prop. etnia",
                              "Prop. inmigrante",
                              "Promedio escolaridad",
                              "Aceptación diversidad apoderados * Promedio discusión en sala"),
        caption = "Aceptar la diversidad en el vecindario",
        caption.above = TRUE,
        file = "reg.html")

webshot2::webshot(url ="reg.html" ,file ="IPO/output/tables/reg.png")
```  


```{r results='asis', message=FALSE, echo=FALSE}  
htmlreg(list(reg4, reg6, reg7, reg11), 
         custom.model.names = c("Modelo 1",
                               "Modelo 2",
                               "Modelo 3",
                               "Modelo 4"
                               ), 
        custom.note = "$***p <$ 0.001, $**p <$ 0.01, $*p <$ 0.05",
        custom.coef.names = c("Intercepto", 
                              "Educación media <br> <i>(Ref. Básica)</i>",
                              "Educación técnica", 
                              "Universidad o posgrado",
                              "Educacion Ns/Nr",
                              "Más de 25 libros <br> <i>(Ref. menos de 25)</i>", 
                              "Aceptación diversidad apoderados", 
                              "Conocimiento cívico D <br> <i>(Ref. Menos que D</i>)", 
                              "Conocimiento cívico C", 
                              "Conocimiento cívico B", 
                              "Conocimiento cívico A", 
                              "Discusión en sala de clases", 
                              "Promedio discusión en sala", 
                              "Prop. etnia", 
                              "Prop. inmigrantes",
                              "Promedio escolaridad",
                              "Aceptación diversidad apoderados * Conocimiento cívico D", 
                              "Aceptación diversidad apoderados * Conocimiento cívico C",
                              "Aceptación diversidad apoderados * Conocimiento cívico B",
                              "Aceptación diversidad apoderados * Conocimiento cívico A",
                              "Aceptación diversidad apoderados * Promedio discusión en sala",
                              "Educación Media * Conocimiento Cívico D",
                              "Educación Técnica * Conocimiento Cívico D",
                              "Educación universitaria * Conocimiento Cívico D",
                              "Educación Ns/Nr * Conocimiento Cívico D",
                              "Educación Media * Conocimiento Cívico C",
                              "Educación Técnica * Conocimiento Cívico C",
                              "Educación universitaria * Conocimiento Cívico C",
                              "Educación Ns/Nr * Conocimiento Cívico C",
                              "Educación Media * Conocimiento Cívico B",
                              "Educación Técnica * Conocimiento Cívico B",
                              "Educación universitaria * Conocimiento Cívico B",
                              "Educación Ns/Nr * Conocimiento Cívico B",
                              "Educación Media * Conocimiento Cívico A",
                              "Educación Técnica * Conocimiento Cívico A",
                              "Educación universitaria * Conocimiento Cívico A",
                              "Educación Ns/Nr * Conocimiento Cívico A"
                              ),
        caption = "Aceptar la diversidad en el vecindario",
        caption.above = TRUE,
        encoding = "UTF-8",
        file = "interac.html")

webshot2::webshot(url ="interac.html" ,file ="IPO/output/tables/interac.png")
```  




```{r}
plot1 <- plot_model(reg4, title = "", show.values = TRUE, value.offset = .35, axis.labels = c("Promedio escolaridad", "Prop. inmigrante alto", "Prop. inmigrante medio", "Prop. etnia alto", "Prop. etnia medio", "Promedio discusión en sala", "Discusión en sala de clases", "Conocimiento cívico (alto)", "Conocimiento cívico (medio)", "Aceptación diversidad apoderados", "Más de 25 libros", "Ns/Nr", "Universidad o postgrado", "Educación Técnica", "Educación media"))

ggsave(plot1, file="IPO/output/graphs/plot1.png")
```


```{r}
int<- plot_model(reg7, type = "int", mdrt.values="minmax", title = "", colors = c("red", "blue")) +
  theme_bw() +
  labs(x = "Aceptación de la diversidad apoderados", y="Aceptación de la diversidad estudiantes", colour = "Promedio discusión") +
  scale_colour_discrete(labels = c("Bajo", "Alto")) +
  scale_y_continuous(limits=c(0,8), breaks = c(0,1,2,3,4,5,6,7)) +
  scale_x_continuous(limits=c(0,7), breaks = c(0,1,2,3,4,5,6,7))


int
ggsave(int, file="IPO/output/graphs/interac.png")
```

## Probar tres niveles

```{r}
reg0.1 <- lmer(est_acc_div ~ 1 + (1 | cod_com_alu) + (1 | cod_com_alu:mrbd), data=base)
reg1.1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + (1 | mrbd) + (1 | cod_com_alu:mrbd), data=base)
reg2.1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + (1 | mrbd) + (1 | cod_com_alu:mrbd), data=base)
reg3.1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + (1 | mrbd) + (1 | cod_com_alu:mrbd), data=base)
reg4.1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd) + (1 | cod_com_alu:mrbd), data=base)
reg7.1 <- lmer(est_acc_div ~ educacion_rec + libros_rec + apod_acc_div*mean_apdis_fa + civic + apdis_fa + mean_apdis_fa + etnia2 + inmigrante2 + escolaridad + (1 | mrbd) + (1 | cod_com_alu:mrbd), data=base)
```

```{r}
screenreg(list(reg0.1, reg1.1, reg2.1, reg3.1, reg4.1, reg7.1))
```