---
title: "variables-tesis"
author: "Kevin Carrasco"
date: "29-11-2021"
output: html_document
---

```{r}
pacman::p_load(haven, dplyr, sjmisc, car, summarytools, webshot, readxl, psych, webshot, kableExtra)
load("IPO/input/data/original/base_est_apod.Rdata")
```

```{r}
data <- base_est_apod %>% dplyr::select(idalumno,
                                        cod_com_alu,
                                        nom_com_alu,
                                      codigoCurso,
                                      mrbd,
                                      est_piel=est_p31_1,
                                      est_clase=est_p31_2,
                                      est_religion=est_p31_3,
                                      est_orien_sexual=est_p31_4,
                                      est_region=est_p31_5,
                                      est_pais=est_p31_8,
                                      est_indigena=est_p31_9,
                                      libros=est_p3,
                                      ap_dis1=est_p15_1,
                                      ap_dis2=est_p15_2,
                                      ap_dis3=est_p15_3,
                                      ap_dis4=est_p15_4,
                                      ap_dis5=est_p15_5,
                                      ap_dis6=est_p15_6,
                                      c_civic=puntaje,
                                      apod_piel=apod_p27_1,
                                      apod_clase=apod_p27_2,
                                      apod_religion=apod_p27_3,
                                      apod_orien_sexual=apod_p27_4,
                                      apod_region=apod_p27_5,
                                      apod_pais=apod_p27_8,
                                      apod_indigena=apod_p27_9,
                                      apod_educ=educ_max
                                       ) %>% as.data.frame(.)
```

```{r}
frq(data$est_piel) #1. si 2. no. 0 y 99 na
frq(data$libros) # de 1 a 5. 0 y 99 na
frq(data$ap_dis1) # de 1 a 4. 0 y 99 na
summary(data$c_civic) # de 1 a 4. 0 y 99 na
frq(data$apod_piel)
```


```{r}
data <- data %>%  set_na(.,
                         na = c(0,99), 
                         drop.levels = TRUE, 
                         as.tag = FALSE) # recode missings de doble marca (99) y vacío (0) a NA

frq(data$est_piel) #1. si 2. no. 0 y 99 na
frq(data$libros) # de 1 a 5. 0 y 99 na
frq(data$ap_dis1) # de 1 a 4. 0 y 99 na
summary(data$c_civic) # de 1 a 4. 0 y 99 na
frq(data$apod_piel)
```

# labels
```{r}
data$est_piel <-factor(data$est_piel, levels = c(1,2), labels = c("Si", "No"))
data$est_clase <-factor(data$est_clase, levels = c(1,2), labels = c("Si", "No"))
data$est_religion <-factor(data$est_religion, levels = c(1,2), labels = c("Si", "No"))
data$est_orien_sexual <-factor(data$est_orien_sexual, levels = c(1,2), labels = c("Si", "No"))
data$est_region <-factor(data$est_region, levels = c(1,2), labels = c("Si", "No"))
data$est_pais <-factor(data$est_pais, levels = c(1,2), labels = c("Si", "No"))
data$est_indigena <-factor(data$est_indigena, levels = c(1,2), labels = c("Si", "No"))


data$apod_piel <-factor(data$apod_piel, levels = c(1,2), labels = c("Si", "No"))
data$apod_clase <-factor(data$apod_clase, levels = c(1,2), labels = c("Si", "No"))
data$apod_religion <-factor(data$apod_religion, levels = c(1,2), labels = c("Si", "No"))
data$apod_orien_sexual <-factor(data$apod_orien_sexual, levels = c(1,2), labels = c("Si", "No"))
data$apod_region <-factor(data$apod_region, levels = c(1,2), labels = c("Si", "No"))
data$apod_pais <-factor(data$apod_pais, levels = c(1,2), labels = c("Si", "No"))
data$apod_indigena <-factor(data$apod_indigena, levels = c(1,2), labels = c("Si", "No"))


label(data$est_piel) <- "Personas de un color de piel distinta a la tuya"
label(data$est_clase) <- "Personas de una clase social distinta a la tuya"
label(data$est_religion) <- "Personas de una religión distinta a la tuya"
label(data$est_orien_sexual) <- "Personas de una orientación sexual distinta a la tuya"
label(data$est_region) <- "Personas que vienen de otra región del país"
label(data$est_pais) <- "Personas que vienen de otro país"
label(data$est_indigena) <- "Personas de origen indígena"

label(data$libros) <- "Cantidad de libros en el hogar"

label(data$ap_dis1) <- "Los profesores estimulan a los estudiantes a formar sus propias opiniones"
label(data$ap_dis2) <- "Los profesores estimulan a los estudiantes a expresar sus opiniones"
label(data$ap_dis3) <- "Los estudiantes plantean hechos políticos de actualidad para ser discutidos en clases"
label(data$ap_dis4) <- "Los estudiantes expresan sus opiniones en clases, aun cuando sean distintas a las de los demás"
label(data$ap_dis5) <- "Los profesores estimulan a los estudiantes a conversar los temas con gente que opina distinto"
label(data$ap_dis6) <- "Los profesores exponen los temas desde los distintos enfoques al explicarlos en clases"

label(data$apod_piel) <- "Personas de un color de piel distinta a la tuya"
label(data$apod_clase) <- "Personas de una clase social distinta a la tuya"
label(data$apod_religion) <- "Personas de una religión distinta a la tuya"
label(data$apod_orien_sexual) <- "Personas de una orientación sexual distinta a la tuya"
label(data$apod_region) <- "Personas que vienen de otra región del país"
label(data$apod_pais) <- "Personas que vienen de otro país"
label(data$apod_indigena) <- "Personas de origen indígena"
label(data$apod_educ) <- "Nivel educacional más alto"
```

```{r include=FALSE}
# Actitudes apoderados
data$apod_piel_rec <- as.numeric(data$apod_piel)
data$apod_clase_rec <- as.numeric(data$apod_clase)
data$apod_religion_rec <- as.numeric(data$apod_religion)
data$apod_orien_sexual_rec <- as.numeric(data$apod_orien_sexual)
data$apod_region_rec <- as.numeric(data$apod_region)
data$apod_pais_rec <- as.numeric(data$apod_pais)
data$apod_indigena_rec <- as.numeric(data$apod_indigena)

data$apod_piel_rec <- car::recode(data$apod_piel_rec, "1=0; 2=1")
data$apod_clase_rec <- car::recode(data$apod_clase_rec, "1=0; 2=1")
data$apod_religion_rec <- car::recode(data$apod_religion_rec, "1=0; 2=1")
data$apod_orien_sexual_rec <- car::recode(data$apod_orien_sexual_rec, "1=0; 2=1")
data$apod_region_rec <- car::recode(data$apod_region_rec, "1=0; 2=1")
data$apod_pais_rec <- car::recode(data$apod_pais_rec, "1=0; 2=1")
data$apod_indigena_rec <- car::recode(data$apod_indigena_rec, "1=0; 2=1")

data <- data %>% rowwise() %>% mutate(apod_acc_div = sum(apod_piel_rec, apod_clase_rec, apod_religion_rec, apod_orien_sexual_rec, apod_region_rec, apod_pais_rec, apod_indigena_rec))

data$apod_acc_div <- sjlabelled::set_label(data$apod_acc_div, 'Aceptación de la diversidad (apoderados)')

# Apertura discusion
data <- data %>% rowwise() %>% mutate(ap_dis = mean(c(ap_dis1, ap_dis2, ap_dis3, ap_dis4, ap_dis5, ap_dis6), na.rm = T))

## estimar EFA
# Análisis Factorial Exploratorio
ap_dis <- data %>% dplyr::select(ap_dis1, ap_dis2, ap_dis3, ap_dis4, ap_dis5, ap_dis6)

colnames(ap_dis) <- c(label(data$ap_dis1), label(data$ap_dis2), label(data$ap_dis3), label(data$ap_dis4), label(data$ap_dis5), label(data$ap_dis6))

psych::fa.parallel(ap_dis, fa="fa")
psych::scree(ap_dis)

fac_ml <- psych::fa(r = ap_dis, nfactors = 2, fm= "ml", rotate = "varimax" )

fac_ml$loadings
# ver https://www.anthonyschmidt.co/post/2020-09-27-efa-tables-in-r/
# Busca funcion para crear tablas FA
source("IPO/processing/fa_table.R") 

# Crea la tabla FA
apdis_fa <-fa_table(fac_ml, .32)
# Exportar la tabla en html
knitr::kable(apdis_fa, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(column = 1,width = "20 cm") %>%
  cat(., file = "IPO/output/tables/apdis_fa.html")
# convertir tabla html en imagen png
webshot(url ="IPO/output/tables/apdis_fa.html", file ="IPO/output/tables/apdis_fa.png", vheight = 10, vwidth = 600)

### el mejor ajuste queda eliminando ap_dis2
puntajes <- psych::fa(r = ap_dis, nfactors = 2, fm= "ml", rotate = "varimax" )$scores
puntajes <- puntajes %>% as.data.frame() %>% dplyr::select(apdis_fa=ML2)
data <- cbind(data, puntajes)

# Conocimiento cívico
data$c_civic <- sjlabelled::set_label(data$c_civic, 'Conocimiento cívico')
data$ap_dis <- sjlabelled::set_label(data$ap_dis, 'Índice apertura a la discusión en el aula')
data$apdis_fa <- sjlabelled::set_label(data$apdis_fa, 'Índice apertura a la discusión en el aula')

# educacion
data$educacion_rec <- ifelse(is.na(data$apod_educ), "Ns/Nr", data$apod_educ) # crea categoria Na para no perder casos
data <- data %>% rowwise() %>%  mutate(educacion_rec = case_when(educacion_rec==1~"Ed Basica",
                                                 educacion_rec==2~"Ed Basica",
                                                 educacion_rec==3~"Ed Basica",
                                                 educacion_rec==4~"Ed Media",
                                                 educacion_rec==5~"Ed Media",
                                                 educacion_rec==6~"Ed Tecnica",
                                                 educacion_rec==7~"Ed Tecnica",
                                                 educacion_rec==8~"Universidad o posgrado",
                                                 educacion_rec==9~"Universidad o posgrado",
                                                 educacion_rec==10~"Universidad o posgrado",
                                                 educacion_rec=="Ns/Nr"~"Ns/Nr"
                                                 )) # recodificar en menos categorias
data$educacion_rec <- factor(data$educacion_rec, levels = c("Ed Basica", "Ed Media", "Ed Tecnica", "Universidad o posgrado", "Ns/Nr")) # relevel porque queda con orden distinto

# libros
data$libros_rec <- as.numeric(data$libros)
data <- data %>% rowwise() %>% mutate(libros_rec = case_when(libros_rec==1 ~ "Menos de 25",
                                                             libros_rec==2 ~ "Menos de 25",
                                                             libros_rec==3 ~ "Más de 25",
                                                             libros_rec==4 ~ "Más de 25",
                                                             libros_rec==5 ~ "Más de 25")) # dejar solo dos categorias
data$libros_rec <- factor(data$libros_rec, levels = c("Menos de 25", "Más de 25"))

# c civic
data$civic <- ntile(data$c_civic,3) # categorizar el puntaje en bajo, medio y alto
data$civic <- factor(data$civic, labels = c("Bajo", "Medio", "Alto"))

# mean ap dis
data <- data %>% group_by(mrbd) %>% mutate(mean_apdis_fa = mean(apdis_fa, na.rm=TRUE)) %>% ungroup()
data <- data %>% group_by(mrbd) %>% mutate(mean_apdis = mean(ap_dis, na.rm=TRUE)) %>% ungroup()

data$civic <- sjlabelled::set_label(data$civic, 'Conocimiento cívico')
data$apdis_fa <- sjlabelled::set_label(data$apdis_fa, 'Índice apertura a la discusión en el aula')
data$mean_apdis <- sjlabelled::set_label(data$mean_apdis, 'Promedio apertura a la discusión en el aula')
data$mean_apdis_fa <- sjlabelled::set_label(data$mean_apdis_fa, 'Promedio apertura a la discusión en el aula')
data$educacion_rec <- sjlabelled::set_label(data$educacion_rec, 'Nivel educacional apoderados')
data$libros_rec <- sjlabelled::set_label(data$libros_rec, 'Cantidad de libros en el hogar')
```

# Guardar bases

```{r}
save(data, file="IPO/input/data/proc/data.RData")
```



# Variables territoriales

Para la elaboración de las tres variables de caracteristicas comunales - cantidad de personas que se identifican con una etnia, cantidad de inmigrantes y promedio de escolaridad - se utilizan datos del CENSO 2017. Estos datos provienen del paquete censo2017 de Mauricio Vargas. Mas informacion en: https://ropensci.org/blog/2021/07/27/censo2017-es/

```{r}
#remotes::install_github("ropensci/censo2017")
library(censo2017)
censo_descargar()

# para usar collect() y expresiones regulares
#remove.packages("cli")
#install.packages("cli")
#install.packages("dbplyr")
#install.packages("devtools")
#devtools::install_github("tidyverse/dbplyr")
library(dplyr)
library(cli)
library(dbplyr)

personas <- tbl(censo_conectar(), "zonas") %>%
  mutate(
    region = substr(as.character(geocodigo), 1, 2),
    comuna = substr(as.character(geocodigo), 1, 5)
  ) %>%
  select(region, comuna, geocodigo, zonaloc_ref_id) %>%
  inner_join(select(tbl(censo_conectar(), "viviendas"),
                    zonaloc_ref_id, vivienda_ref_id), by = "zonaloc_ref_id") %>%
  inner_join(select(tbl(censo_conectar(), "hogares"), vivienda_ref_id,
                    hogar_ref_id), by = "vivienda_ref_id") %>%
  inner_join(select(tbl(censo_conectar(), "personas"), hogar_ref_id,
                    p08, p15, p18), by = "hogar_ref_id") %>%
  collect()

# identificar variable y categorias
tbl(censo_conectar(), "variables_codificacion") %>%
  collect() %>%
  filter(variable == "p16")

# Cantidad de personas que se identifican con alguna etnia
comuna_etnia <- tbl(censo_conectar(), "personas") %>%
  select(p10comuna, p16) %>%
  filter(p16==1) %>% 
  group_by(p10comuna, p16) %>%
  count() %>%
  # re-ordeno las etiquetas, lo hago en esta parte por eficiencia
  mutate(
   etnia = ifelse(p16 == 1, "1. Si", NA)
  ) %>%
  ungroup() %>%
  collect()

comuna_etnia <- comuna_etnia %>% select(p10comuna, etnia=n)

# Cantidad de personas inmigrantes
tbl(censo_conectar(), "variables") %>%
  collect() %>%
  filter(grepl("Pais", descripcion))

tbl(censo_conectar(), "variables_codificacion") %>%
  collect() %>%
  filter(variable == "p12pais")


comuna_inm <- tbl(censo_conectar(), "personas") %>%
  select(p10comuna, p12pais) %>%
  group_by(p10comuna, p12pais) %>%
  count() %>%
  ungroup() %>%
  collect()
  
comuna_inm <- comuna_inm %>% mutate(inmigrante = ifelse((p12pais==997), 0,
                                                        ifelse((p12pais==998), 0,
                                                               ifelse((p12pais==999), 0, 1))))

comuna_inm <- comuna_inm %>% group_by(p10comuna) %>% mutate(inmigrante = sum(inmigrante))   

comuna_inm <- comuna_inm %>% filter(!duplicated(p10comuna))                 

comuna_inm <- comuna_inm %>% select(p10comuna, inmigrante)

# Promedio de escolaridad
tbl(censo_conectar(), "variables") %>%
  collect() %>%
  filter(grepl("Curso", descripcion))

tbl(censo_conectar(), "variables_codificacion") %>%
  collect() %>%
  filter(variable == "p15")



comuna_esc <- tbl(censo_conectar(), "personas") %>%
  select(p10comuna, p15, p09) %>%
  filter(p09>=18) %>% 
  select(p10comuna, p15, -p09) %>%
  filter(p15<98) %>% 
  group_by(p10comuna) %>%
  # re-ordeno las etiquetas, lo hago en esta parte por eficiencia
  mutate(
    escolaridad = mean(p15, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  collect()

comuna_esc <- comuna_esc %>% filter(!duplicated(p10comuna)) %>% select(p10comuna, escolaridad)

## ahora lo mismo pero con proporciones
# proporcion de personas que se identifican con alguna etnia
prop_etnia <- tbl(censo_conectar(), "personas") %>%
  group_by(p10comuna, p16) %>%
  count() %>% 
  ungroup() %>%
  collect()

prop_etnia <- prop_etnia %>% mutate(p = n / sum(n))

prop_etnia <- prop_etnia %>% filter(p16==1) %>% # dejamos solo quienes si se identifican
  select(p10comuna, prop_etnia=p)

# Cantidad de personas inmigrantes
tbl(censo_conectar(), "variables_codificacion") %>%
  collect() %>%
  filter(variable == "p12pais")

prop_inm <- tbl(censo_conectar(), "personas") %>%
  select(p10comuna, p12pais) %>%
  group_by(p10comuna, p12pais) %>%
  count() %>%
  ungroup() %>%
  collect()

prop_inm <- prop_inm %>% mutate(p = n / sum(n))

prop_inm <- prop_inm %>% dplyr::filter(p12pais!=997) 
prop_inm <- prop_inm %>% dplyr::filter(p12pais!=998) 
prop_inm <- prop_inm %>% dplyr::filter(p12pais!=999)
                                       
prop_inm <- prop_inm %>% group_by(p10comuna) %>% mutate(prop_inm = sum(p))                             

prop_inm <- prop_inm %>% select(p10comuna, prop_inm) %>% filter(!duplicated(p10comuna)) 

# merge bases

data_territorio <- merge(comuna_esc, comuna_etnia, by="p10comuna")
data_comuna <- merge(data_territorio, comuna_inm, by="p10comuna")
data_comuna <- merge(data_comuna, prop_etnia, by="p10comuna")
data_comuna <- left_join(data_comuna, prop_inm, by="p10comuna")

data_comuna$prop_inm <- ifelse((is.na(data_comuna$prop_inm)), 0, data_comuna$prop_inm)



save(data_comuna, file="IPO/input/data/proc/data_comuna.RData")

```

